stages:
  - lint

variables:
  POSTGRES_USER: 'fmm'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_fmm'
  POSTGRES_HOST_AUTH_METHOD: trust


flake8:
  stage: lint
  image: python:3.7-alpine
  before_script:
    - pip install -q flake8
  script:
    - flake8
