# Generated by Django 3.0.3 on 2020-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200527_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptptransaction',
            name='currency',
            field=models.TextField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('UAH', 'UAH'), ('BYN', 'BYN'), ('KZT', 'KZT')], default='INR', editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.TextField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('UAH', 'UAH'), ('BYN', 'BYN'), ('KZT', 'KZT')], default='INR', editable=False),
        ),
    ]
