# Generated by Django 3.0.3 on 2020-09-15 13:36

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(storage=config.storage_backends.TestimonialStorage(), upload_to=''),
        ),
    ]
