# Generated by Django 3.0.3 on 2020-05-29 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200529_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducation',
            name='achievements',
        ),
        migrations.AddField(
            model_name='usermentoraccount',
            name='achievements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, max_length=25, size=None),
        ),
    ]
