# Generated by Django 3.0.3 on 2020-07-24 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200724_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinfo',
            name='yuwee_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='phone',
            field=models.CharField(default=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone has to be numeric and from 11 to 13 characters', regex='^(\\+\\d{1,3}[- ]?)?\\d{10}$')]),
            preserve_default=False,
        ),
    ]
