# Generated by Django 3.0.3 on 2020-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200731_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermentoraccount',
            options={'ordering': ('top', 'created_at')},
        ),
        migrations.AddField(
            model_name='usermentoraccount',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
