# Generated by Django 3.0.3 on 2020-10-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200917_1048'),
        ('user', '0012_auto_20200726_1900'),
    ]

    operations = [
    ]
