# Generated by Django 3.0.3 on 2020-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_auto_20200915_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
