# Generated by Django 3.0.3 on 2020-09-20 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
