# Generated by Django 3.0.3 on 2020-05-11 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import fmm.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200509_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMentorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', fmm.utils.fields.DayOfTheWeekField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=25)),
                ('start_at', models.TimeField(default=datetime.time(10, 0))),
                ('end_at', models.TimeField(default=datetime.time(19, 0))),
                ('timezone', models.CharField(default='UTC', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='user.UserMentorAccount')),
            ],
            options={
                'db_table': 'user_mentor_schedule',
                'ordering': ('id',),
            },
        ),
    ]
