# Generated by Django 3.0.3 on 2020-07-13 18:58

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='FAQ title', max_length=250, unique=True, verbose_name='Title')),
                ('body', models.TextField(help_text='1000 words', verbose_name='Body')),
                ('status', models.BooleanField(default=False, verbose_name='Active FAQ')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
