# Generated by Django 3.0.3 on 2020-05-28 09:51

from django.db import migrations, models
import django.db.models.deletion
import fmm.study.models
import fmm.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20200527_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='presentation',
            field=models.ImageField(blank=True, null=True, storage=fmm.utils.storage.OverwriteStorage(), upload_to=fmm.study.models.workshop_presentation_upload_path),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='presentation',
            field=models.ImageField(blank=True, null=True, storage=fmm.utils.storage.OverwriteStorage(), upload_to=fmm.study.models.workshop_presentation_upload_path),
        ),
        migrations.AlterField(
            model_name='workshopuser',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workshop_users', to='study.WorkshopCoupon'),
        ),
    ]
