# Generated by Django 3.0.3 on 2020-07-20 20:36

from django.db import migrations, models
import fmm.study.models
import fmm.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_auto_20200703_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=fmm.utils.storage.OverwriteStorage(), upload_to=fmm.study.models.workshop_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=fmm.utils.storage.OverwriteStorage(), upload_to=fmm.study.models.workshop_picture_upload_path),
        ),
    ]
