# Generated by Django 3.0.3 on 2020-08-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_auto_20200731_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcall',
            name='call_id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
