# Generated by Django 3.0.3 on 2020-09-07 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0016_workshop_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorPayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_signature', models.CharField(max_length=225)),
                ('razorpay_payment_id', models.CharField(max_length=225)),
                ('razorpay_order_id', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razor_pay_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RazorPayPayment',
                'ordering': ('id',),
            },
        ),
    ]
