# Generated by Django 3.0.3 on 2020-05-09 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200509_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermentoraccount',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='usermentoraccount',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checked_mentor_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermentoraccount',
            name='status',
            field=models.CharField(choices=[('NOT_APPLIED', 'Not applied'), ('WAITING_APPROVAL', 'Waiting for approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_APPLIED', max_length=255),
        ),
    ]
