# Generated by Django 3.0.3 on 2020-05-28 09:43

from django.db import migrations, models
import fmm.user.models
import fmm.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200527_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=fmm.utils.storage.OverwriteStorage(), upload_to=fmm.user.models.user_avatar_path),
        ),
    ]
