# Generated by Django 3.0.3 on 2020-05-15 19:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_usermentorschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0003_workshoprecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=4000)),
                ('hidden_content', models.TextField(blank=True, max_length=2000, null=True)),
                ('mark', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_reviews', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_reviews', to='study.Workshop')),
            ],
            options={
                'db_table': 'workshop_review',
                'ordering': ('id',),
                'unique_together': {('user', 'workshop')},
            },
        ),
        migrations.CreateModel(
            name='MentorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=4000)),
                ('hidden_content', models.TextField(blank=True, max_length=2000, null=True)),
                ('mark', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_reviews', to='user.UserMentorAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_review',
                'ordering': ('id',),
                'unique_together': {('user', 'mentor')},
            },
        ),
    ]
