# Generated by Django 3.0.3 on 2020-05-14 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcoupon',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='StudyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='study_payments', to='payment.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_payment',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='appointmentuser',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_users', to='study.StudyPayment'),
        ),
        migrations.AddField(
            model_name='workshopuser',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workshop_users', to='study.StudyPayment'),
        ),
    ]
