# Generated by Django 3.0.3 on 2020-09-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_groupcall_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='room_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
