# Generated by Django 3.0.3 on 2020-09-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0018_auto_20200907_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
