# Generated by Django 3.0.3 on 2020-06-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20200529_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=250)),
                ('token', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'group_call',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='group_call',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment', to='study.GroupCall'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='group_call',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workshop', to='study.GroupCall'),
        ),
    ]
