# Generated by Django 3.0.3 on 2020-06-19 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0008_auto_20200618_1937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workshopuser',
            unique_together={('user', 'workshop')},
        ),
    ]
